### ISSUE TITLE
Option for including local boost libraries?

### ISSUE THREAD

**Issue by vsilv** [jeaye/color_coded#100]
I noticed that you are using an older version of boost than my system uses-  In particular I had no problem in reconfiguring your boost_cmake, but it becomes a little bit messy.. Why dont search for boost libraries and check the version? This would be a more elegant solution than using this static library! I would also recommend for clang to search for it and check for the version, it would be easier than fiddling around with those flags.

**Comment by jeaye** [comment]
> Why dont search for boost libraries and check the version?

color_coded is being used on dozens of platforms. Some of those platforms don't use a modern enough boost for color_coded to be able to compile. Other platforms have a newer version of boost, yes, but there's no benefit of allowing both; the boost we have works fine now (aside from its compiler warnings) and it'll stay for some time longer. color_coded use to use the system's boost; it simply wasn't reliable.

> I would also recommend for clang to search for it and check for the version

The system isn't guaranteed to have clang at all. color_coded provides a stable, known-to-work clang version and it upgrades as soon as a new stable release comes out. 3.7 is excluded in this, since it's not a proper release (they forgot to package libclang.a -_-).

> it would be easier than fiddling around with those flags

Unless you have a very specific reason to use your system's clang, color_coded will do just fine with C++11 and C++14. If you go out of your way to use the system's clang, yeah, you'll need to toy with some flags.

**Comment by vsilv** [comment]
Thank you for answering the question! I guess the issue with the reliability is much more important than I had in mind before.

**Comment by jeaye** [comment]
No problem. Thanks for understanding.
