### ISSUE TITLE
Inconsistent member function highlighting

### ISSUE THREAD

**Issue by jdrouhard** [jeaye/color_coded#117]
This may be a clang bug (or by design), but might need to be addressed or worked around for the syntax highlighting.

Trying to syntax highlight the following file yields different cursor kinds (and thus highlight groups) for the `foo()` invocations in the `bar()` implementation:

``` c++
template<typename T>
struct A {
    void foo(void);
    void foo(int);
};

struct B {
    void foo(int);
};

template <typename T>
struct X {
    A<int> a_int;
    A<T> a_t;
    B b;

    void bar() {
        a_int.foo(5);
        a_t.foo(5);
        b.foo(5);
    }
};

int main() {
    X<int> x;
    x.bar();
}
```

`a_int.foo()` has an `OverloadedDeclRef` type for `foo()`, where the other two yield a pair of `CallExpr`/`MemberRefExpr` cursor kinds. I used your clangtest.cpp file from a couple clang bug reports you filed to get the following:

```
foo, 3:5 -> 3:19, CXXMethod, FunctionProto, foo()
foo, 4:5 -> 4:18, CXXMethod, FunctionProto, foo(int)
foo, 8:5 -> 8:18, CXXMethod, FunctionProto, foo(int)
a_int, 13:5 -> 13:17, FieldDecl, Unexposed, a_int
a_t, 14:5 -> 14:13, FieldDecl, Unexposed, a_t
b, 15:5 -> 15:8, FieldDecl, Record, b
a_int, 18:9 -> 18:14, MemberRefExpr, Unexposed, a_int
foo, 18:15 -> 18:18, OverloadedDeclRef, Invalid, foo
a_t, 19:9 -> 19:12, MemberRefExpr, Unexposed, a_t
foo, 20:9 -> 20:17, CallExpr, Dependent, foo
foo, 20:9 -> 20:14, MemberRefExpr, Unexposed, foo
b, 20:9 -> 20:10, MemberRefExpr, Record, b
foo, 18:9 -> 18:21, CallExpr, Void, foo
foo, 18:9 -> 18:18, MemberRefExpr, Unexposed, foo
a_int, 18:9 -> 18:14, MemberRefExpr, Unexposed, a_int
foo, 19:9 -> 19:19, CallExpr, Void, foo
foo, 19:9 -> 19:16, MemberRefExpr, Unexposed, foo
a_t, 19:9 -> 19:12, MemberRefExpr, Unexposed, a_t
foo, 20:9 -> 20:17, CallExpr, Void, foo
foo, 20:9 -> 20:14, MemberRefExpr, Unexposed, foo
b, 20:9 -> 20:10, MemberRefExpr, Record, b
```

It seems odd to me that all member variables _and_ member functions are highlighted with the same `MemberRefExpr` clang kind, and there's no way to distinguish them. Except, they _are_ different when the member function is specifically overloaded with templates as in the example, causing different highlighting for functions in different contexts for no seemingly apparent reason. Preferably, all the `foo()` calls in `bar()` should be a different clang cursor kind than `a_int`, `a_t`, and `b`.

Let me know if there's anything else I can do to help track this down or fix it up.

**Comment by johnmiked15** [comment]
It seems like the `OverloadedDeclRef` is being used for the first example, even though the clang parser is also returning a `MemberRefExpr` for it:
```
foo, 18:15 -> 18:18, OverloadedDeclRef, Invalid, foo
foo, 18:9 -> 18:21, CallExpr, Void, foo
foo, 18:9 -> 18:18, MemberRefExpr, Unexposed, foo
```

Is there a way to change the parsing code in color_coded to utilize the `CallExpr` that comes in instead of the `MemberRefExpr`? I haven't looked at the code yet and I'm not too familiar with how the clang AST works, but it seems like it might be doable.

**Comment by jeaye** [comment]
@johnmiked15 Ah, we may be able to just ignore `OverloadedDeclRef` and highlight `CallExpr` instead. If I remember correctly, and I probably don't since this was a couple of years ago, `CallExpr` may be the token used here, but it'll be incorrect in other places and there's no way to please clang.

However, I have no interest in discouraging you, if you want to tinker, and I'd love to merge in a fix for this. The mapping of clang token to highlight group is done here: https://github.com/jeaye/color_coded/blob/master/include/clang/token.hpp I can give you a brief overview; a lot of the code is just RAII wrapping around libclang and safety wrapping around viml.

The async queue has a compilation task here: https://github.com/jeaye/color_coded/blob/master/include/core.hpp#L58 which loads config, builds a translation unit, extracts a token pack, and stores it. Once vim has the chance to check the queue, it jumps to: https://github.com/jeaye/color_coded/blob/master/include/vim/highlight.hpp which will map each token and call into vim. That's run from: https://github.com/jeaye/color_coded/blob/master/include/vim/buffer.hpp
