### ISSUE TITLE
Question: color_coded isn't coloring anything, am I missing something?

### ISSUE THREAD

**Issue by TheZoc** [jeaye/color_coded#141]
Hello,

I apologize for asking such question, but I'm having some trouble.

I'm trying to use color_coded on this project: https://github.com/TheZoc/ZPatcher

I initially attempted using YCM-Generator, I got this:
```
:! /Users/zoc/.vim/bundle/YCM-Generator/config_gen.py -F cc  '/Users/zoc/github/ZPatcher' </dev/null
Preparing build directory...
$ make clean

Running make...
$ make -i -j8
Build completed in 2.1 sec

Collected 42 relevant entries for C compilation (0 discarded).
Collected 34 relevant entries for C++ compilation (0 discarded).
Created CC config file with 1 C flags

Press ENTER or type command to continue
```

and on `:CCerror`, I got `/Users/zoc/github/ZPatcher/ZLauncher/stdafx.h:12:10: fatal error: 'wx/wxprec.h' file not found`

Then I built my own .color_coded file:
```
-x
-c
-Wall
-Wextra
-std=c++14
-Wno-unused-parameter
-Wno-unused-variable
-I/usr/local/lib/wx/include/osx_cocoa-unicode-3.1
-I/usr/local/include/wx-3.1
-Ilibs/LzmaLib/source
-Ilibs/tinyxml2
-D_FILE_OFFSET_BITS=64
-DwxDEBUG_LEVEL=0
-DWXUSINGDLL
-D__WXMAC__
-D__WXOSX__
-D__WXOSX_COCOA__
-llzma
-lpthread
-lcurl
-ltinyxml2
-L/usr/local/lib
-framework IOKit
-framework Carbon
-framework Cocoa
-framework AudioToolbox
-framework System
-framework OpenGL
-lwx_osx_cocoau_webview-3.1
-lwx_osx_cocoau_xrc-3.1
-lwx_osx_cocoau_html-3.1
-lwx_osx_cocoau_qa-3.1
-lwx_osx_cocoau_adv-3.1
-lwx_osx_cocoau_core-3.1
-lwx_baseu_xml-3.1
-lwx_baseu_net-3.1
-lwx_baseu-3.1
```

But now, when I try using `:CCerror` with my configuration, I get the message: `internal error: cannot retrieve location`

and.. I don't know what else to do.

I apologize for this, which might be a basic question, but I'm still learning the ropes while switching from Windows to macOS.

Can you, please, help me with this issue? 😀 

Thank you very much in advance!

**Comment by jeaye** [comment]
Hey, thanks for trying out color_coded. Let's see if we can get this working for you. I've cloned your project and copied in your manual `.color_coded`.

When I ran `gvim ZUpdater/Main.cpp`, then `:CCerror`, I saw this:

```text
/var/folders/g4/80jnzcq54n17y2d0gvdvszb40000gn/T/color_coded-501/Main.cpp:19:10: fatal error: 'ApplyPatch.h' file not found
```

So, clang didn't know where to find `ApplyPatch.h`. No problem; I can see that it's in `./ZPatcherLib`, so I'll add that to the `.color_coded` file. Now I can view all three `Main.cpp` files and `:CCerror` reports `no errors`. Here's the final `.color_coded` (with only one line added and a bunch removed):

```text
-IZPatcherLib
-I/usr/local/lib/wx/include/osx_cocoa-unicode-3.1
-I/usr/local/include/wx-3.1
-Ilibs/LzmaLib/source
-Ilibs/tinyxml2
-D_FILE_OFFSET_BITS=64
-DwxDEBUG_LEVEL=0
-DWXUSINGDLL
-D__WXMAC__
-D__WXOSX__
-D__WXOSX_COCOA__
```

Note that I've removed all the `-W` flags, since warnings don't matter in color_coded. I've also removed all of the linker flags (`-l` and `-L`), since libclang just compiles code; it doesn't link anything. All you need to specify are your includes and defines, typically.

Hopefully this clears up some of the magic. Make sure that, when you use color_coded, you're using a colorscheme which has been altered to support all of the additional highlight groups. The README covers that here: https://github.com/jeaye/color_coded#highlighting

**Comment by TheZoc** [comment]
Hey @jeaye! Thank you very much for your reply! 😁 

After adding that content to the file, it worked!

So I decided to do some experimenting form my original file (so I could learn for future attempts).
Apparently the `-x` flag causes the issue `internal error: cannot retrieve location`, even if I set it as `-x c++`. That `-x` flag was automatically added by YCM-Generator and is present on YCM config (Without the c++ part).
Maybe this is an issue that should be further inspected? (I apologize, I'm still new to all of this, so `-x c++` might not even be the correct syntax).

Ah, yeah, `-framework` flags doesn't work on .color_coded.

`-c` flag gave me an issue about Objective-C earlier on but it seems to have disappeared. Maybe I just needed to rename the file to `.color_coded_cpp`?

Still, thank you very much, it seems to be working without errors now 😃 

Okay, may I abuse a bit of your kindness and ask two more questions?

- First, about the colors, I'm using `solarized` theme for a while, I really like it. Does it have known issues?
I remember that I had to disable "Draw bold text in bright colors" in iTerm2 because solarized didn't support bright colors correctly. (Thought that information might be useful here).

- Also, does color_coded support different platforms?
For example, Having a `.color_coded_%language%_%platform%`? While I'll be in macOS for a while, I'll probably need to get linux to check if that code works flawlessly in there too, and wxWidgets defines a bunch of platform specific macros.

Thank you very much for your work, it's impressive to see it running! 😎

**Comment by jeaye** [comment]
> Maybe this is an issue that should be further inspected? (I apologize, I'm still new to all of this, so -x c++ might not even be the correct syntax).

`-x` is specified for you, by color_coded, based on the buffer's filetype. Specifying it yourself will only make things more complex, so note that I didn't include it in the `.color_coded` I shared with you above.

`-c` doesn't make sense with color_coded either, since color_coded is already just compiling and `-c` means to compile without linking. I recommend you stop adding all of these flags and just worry about what's needed for clang to understand your code (defines and include paths); it and color_coded will take care of the rest.

> First, about the colors, I'm using solarized theme for a while, I really like it. Does it have known issues?

You'll need to check that the solarized theme you're using has all of the highlight groups for color_coded. I've linked to the section of the readme, in my previous comment, where they're described. You'll need to open up the solarized theme and add those groups if you want to see the highlighting for them; if you don't, color_coded will still work, but you won't get the richest highlighting.

> While I'll be in macOS for a while, I'll probably need to get linux to check if that code works flawlessly in there too, and wxWidgets defines a bunch of platform specific macros.

There are no platform-specific `.color_coded` files as there are filetype-specific ones. Although wxWidgets may internally use macros and defines, all that matters is what *you* have to specify to the compiler when *you* build. Typically, those flags are quite similar across similar platforms. If worst comes to worst, you can use different .color_coded files for the different machines (maybe the repo contains a script to generate one for that platform). I've never hit a case where this was actually needed though.

> Thank you very much for your work, it's impressive to see it running!

Thanks for taking the time to get it running. Enjoy!

**Comment by TheZoc** [comment]
Thank you very much for all these explanations :D

If someone ever find this issue through Google, there is a "solarizeded" theme that is a solarized theme with color_coded support. It's possible to find it in this repository: https://github.com/NigoroJr/color_coded-colorschemes
