### ISSUE TITLE
Consider Using YCM Conf

### ISSUE THREAD

**Issue by starcraftman** [jeaye/color_coded#18]
Just a suggestion, I haven't looked at your code. When `.color_coded` isn't present, you could fallback to parsing `.ycm_extra_conf.py` flags var, just need to read all the lines and strip quotes/commas.

**Comment by jeaye** [comment]
YCM's configuration file can contain arbitrary Python functions and code. To reliably parse it, we'd need a Python interpreter embedded in color_coded. This has been raised before and I've turned it down, since it's not very reliable. #15 is trying to get the data from CMake and other places; that's more likely.
