### ISSUE TITLE
Can color_coded attempt to look for an installed version of clang+llvm?

### ISSUE THREAD

**Issue by tony** [jeaye/color_coded#39]
> For various compatibility reasons, color_coded will attempt to download a known version of clang. This may add time to your configuration process, but it offers more stability across multiple platforms.

Is it possible for clang to look for a particular version of llvm / clang on the system? What would be the possible issues that could arise?

**Comment by jeaye** [comment]
Let's take Lua for example. Lua has been the bane of my support work for color_coded. I have dumped hours of time on people's different setups, whether they have multiple Lua installations, or they're running LuaJIT, or they're running a newer/later version of it, or maybe they don't even have it.

I ship clang with color_coded because, if I don't, there _will_ be issues. Now that we've stabilized your color_coded setup, we can look into what it'd take for you to use your system clang.

With all of that said, give me a bit to tinker with some changes. If I can get system-level clang working on my machine then I'll add it to the build system and label it as unsupported. I'll report back here by tonight (noon now).

**Comment by jeaye** [comment]
@tony I have pushed up some changes, including documentation. You can start by looking here: https://github.com/jeaye/color_coded#how-can-i-use-a-custom-llvmclang-setup

Let me know how this works for you; I've tried it on Arch and Ubuntu with success.

**Comment by jeaye** [comment]
Looks like you have this working. ;)
