### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by UnrealQuester** [jeaye/color_coded#47]
I would like to know your stance on adding unit tests. These could be automatically checked by travis and make it easier for potential contributors to add/modify code without breaking existing functionality. It also complements the existing documentation.
As I would like to add some tests, may I nominate [Catch](https://github.com/philsquared/Catch) as our testing framework? It is fairly lightweight as it is packed up as a single header file.

**Comment by jeaye** [comment]
Unit tests weren't written for color_coded initially, since so much of the input depends on vim and is almost entirely side-effect based. That is to say, there are very few systems which are purely functional in color_coded, since most of them end up calling into lua (which calls into vim). The most functional thing to unit tests (as far as inputs and outputs) would be the clang compilation itself, but that seems redundant. Unlike my library and compiler projects, I haven't been too concerned about unit and functional testing with color_coded, but that doesn't mean it wouldn't be nice.                                                                                   

I have my own framework, [jest](https://github.com/jeaye/jest), which I use on [a](https://github.com/jeaye/jeayeson) [number](https://github.com/jeaye/jtl) [of](https://github.com/jeaye/jank) [projects](https://github.com/jeaye/juble) and would use in color_coded, if anything.

**Comment by jeaye** [comment]
Shall we close this, since we've started along the unit testing path or would you like to leave this open until we have more coverage?

**Comment by UnrealQuester** [comment]
I only opened this issue to test the waters. As we have a make target and test framework now, I feel like this issue can be closed. But this is up to you.
