### ISSUE TITLE
Behaviour is dependent upon $CWD

### ISSUE THREAD

**Issue by dickontoo** [jeaye/color_coded#54]
There's a small issue with the CWD affecting color_coded's behaviour: it appears to load the .color_coded file from where it was launched, rather than the directory of the source file you're editing:

    newdesktop:/home/dickon/src/omxtx/ (0) 79 $ strace -f gvim omxtx.c 2>&1 | grep '\.color_coded'
    [pid 19898] open("./.color_coded", O_RDONLY) = 5
    newdesktop:/home/dickon/ (0) 82 $ strace -f gvim src/omxtx/omxtx.c 2>&1 | grep '\.color_coded'
    [pid 20280] open("./.color_coded", O_RDONLY) = 5

resulting in incorrect flags and whatnot being applied.  I don't know what the right answer is, but felt it worth flagging.  I'm fairly sure colouring behaviour shouldn't be dependent on where you launch the editor from.

Love the project.  It's really helpful catching typoes.

**Comment by jeaye** [comment]
On Tue, May 19, 2015 at 06:29:47AM -0700, Dickon Hood wrote:
>    There's a small issue with the CWD affecting color_coded's behaviour: it
>    appears to load the .color_coded file from where it was launched, rather
>    than the directory of the source file you're editing:

This is intended behavior. The reasoning is that vim should be opened in your project's directory, same goes for YCM. color_coded currently handles only a single .color_coded file at a time, so choosing that file based on the opened files will be haphazard. As an example:

```bash
# Which .color_coded should it look for?
gvim src/main.cpp lib/foo/src/main.cpp
```

To remedy this, it looks in $CWD, as you found. If you have some suggestions on how we can work around this in a good way, let me know. Otherwise, I hope it's not a big issue.

>    Love the project. It's really helpful catching typoes.

Thanks for checking it out; I hope it suits you well.

**Comment by dickontoo** [comment]
You make a very good point, and one I don't have an answer for.  I'll just have to be more careful about where I start the editor from in future.
