### ISSUE TITLE
Ubuntu required packages

### ISSUE THREAD

**Issue by tony** [jeaye/color_coded#59]
`sudo apt-get install libclang-3.6-dev` was a dependency for me. "clang-c/cxstring.h" was requested.

Can anyone on ubuntu confirm?

**Comment by jeaye** [comment]
It certainly won't hurt to have it, so I've added it for now (lest others run into a similar issue). One question though, was this during the compilation of color_coded, or during its usage?

**Comment by tony** [comment]
This was during ``make`` without ``libclang-3.6-dev``.

**Comment by tony** [comment]
So far all is up to snuff with FreeBSD also. Keepin an eye on things.

Actually, I lied, I meant on *debian*.  But the README alteration is still correct.

**Comment by jeaye** [comment]
During compilation, color_coded should look to the clang distribution it downloads for the includes. On your Debian setup, did you have it download clang? If you copied your FreeBSD setup, where you use a custom clang, you might run into some issues.

If you downloaded clang, as per the normal color_coded process, you *shouldn't* need it installed on the system in order to build.
