### ISSUE TITLE
Support clang compilation database

### ISSUE THREAD

**Issue by octol** [jeaye/color_coded#90]
A robust way of parsing C++ code is to use the clang compilation database, `compile_commands.json`. Please add support for this in addition to the already existing configuration file.

**Comment by UnrealQuester** [comment]
You can do this indirectly by using [YCM-Generator](https://github.com/rdnetto/YCM-Generator). There was also some discussion in #15 about this.

**Comment by jeaye** [comment]
I agree with @UnrealQuester. YCM-Generator handles this; if you want to use non-color_coded configuration, it makes sense to take advantage of a non-color_coded tool. Furthermore, YCM-Generator can also integrate right into Vim so you can generate configs without leaving the editor.

We can document this more in the README, admittedly.

**Comment by octol** [comment]
I briefly looked into YCM-Generator, but I did not see this functionality, all I managed to get running was generating a .color_coded file.

**Comment by jeaye** [comment]
> all I managed to get running was generating a .color_coded file.

That's the goal!

> Using clang compilation databases would give you the ability to have file-specific compiler flags.

We currently allow per-filetype, but not per-file compiler flags. I think this is an edge case which is not very common, hence the lack of support for it. Now that I understand your final goal, I'll reopen this and mark it accordingly. Note that I consider this low priority.

However, if you're interested in making the change, I'd love to see a PR.

**Comment by octol** [comment]
Thanks for reopening the issue. Yes I understand if it's currently low priority.

**Comment by UnrealQuester** [comment]
I tried to implement this and found an interesting bug. Not shure if this might be a show stopper or not. The command in the compilation database (generated by cmake) looks like this:
````
/usr/bin/c++
-std=c++11
-I/some/absolute/include/path
-o
CMakeFiles/path/to/object.cpp.o
-c
/absolute/path/to/file.cpp
```
For some reason, clang does not seem to like the '-c /absolute/path/to/file.cpp' and just crashes during parsing. If I remove that, everything works fine.
Maybe we can just run a filter on the output, if this is indeed a clang bug.

**Comment by jeaye** [comment]
>    For some reason, clang does not seem to like the '-c
>    /absolute/path/to/file.cpp' and just crashes during parsing. If I remove
>    that, everything works fine.
>    Maybe we can just run a filter on the output, if this is indeed a clang
>    bug.

As far as I know, the -c flag just specifies that the file the file is
not to be turned into an executable, but just compiled. The man page for
clang says "Run all of the above, plus the assembler, generating a
target ".o" object file." Furthermore, the -c flag doesn't take an
argument.

So, why are you passing the absolute path after -c? color_coded will
give libclang the path of the file, which is not necessarily the path of
the file being edited (temporary files may be used); when you specify
this path here, you're confusing libclang.

Furthermore, -c is already added by color_coded, since it doesn't make
sense to not compile without it here. I'll briefly summarize.

1) -c is redundant; don't specify it
2) -c doesn't take arguments, so you're just giving clang a file name,
which it's going to try to use as the file to compile. That conflicts
with the usage within color_coded; don't specify the file

The relevant code which uses the args and the file name to make a
translation unit is here:
https://github.com/jeaye/color_coded/blob/master/include/clang/translation_unit.hpp

The default arguments, per file type, which includes -c, are here:
https://github.com/jeaye/color_coded/blob/master/include/conf/defaults.hpp

**Comment by UnrealQuester** [comment]
The flags I posted are generated by CMake and written to compile_commands.json. I have no control over them.

> 2) -c doesn't take arguments, so you're just giving clang a file name,
> which it's going to try to use as the file to compile. That conflicts
> with the usage within color_coded; don't specify the file

This is indeed what was causing the problem. Looks like this has to be stripped out before it gets passed to compile().

**Comment by jeaye** [comment]
Closed with https://github.com/jeaye/color_coded/pull/99

**Comment by 4pao** [comment]
YCM-generator handle this poorly. When we work on a project with complicated configuration process, it is relatively easy to get a "compile_commands.json" than recreate compilation process by hand. Some project (pytorch for example) with python setup driving cmake process, we don't even know how it was configured but a compile_comands.json was already there.
